import { FormEvent, useEffect, useState } from "react";

import "./TimelineWorkspace.css";

type ActiveCase = {
  investigation_id: string;
  status: string;
  evidence_item_count: number;
  analysis_run_count: number;
};

type TimelineEvent = {
  event_id: number;
  investigation_id: string;
  created_at: string;
  event_type: string;
  actor_type: "system" | "operator";
  actor_label: string;
  summary: string;
  details: Record<string, unknown>;
};

type Props = {
  activeCase: ActiveCase | null;
  unavailable: boolean;
  onError: (message: string) => void;
  onNotice: (message: string) => void;
};

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, init);
  const payload = await response.json();
  if (!response.ok) {
    const detail = typeof payload?.detail === "string" ? payload.detail : `Timeline request failed with HTTP ${response.status}.`;
    throw new Error(detail);
  }
  return payload as T;
}

const label = (value: string) => value.replaceAll("_", " ");

export function TimelineWorkspace({ activeCase, unavailable, onError, onNotice }: Props) {
  const [events, setEvents] = useState<TimelineEvent[]>([]);
  const [newestFirst, setNewestFirst] = useState(false);
  const [author, setAuthor] = useState("Rafael");
  const [note, setNote] = useState("");
  const [loading, setLoading] = useState(false);
  const caseVersion = activeCase ? `${activeCase.investigation_id}:${activeCase.status}:${activeCase.evidence_item_count}:${activeCase.analysis_run_count}` : "none";

  async function loadTimeline() {
    if (!activeCase) { setEvents([]); return; }
    setLoading(true);
    try {
      setEvents(await request<TimelineEvent[]>(`/api/investigations/${activeCase.investigation_id}/timeline?newest_first=${newestFirst}`));
    } catch (caught) {
      onError(caught instanceof Error ? caught.message : "Timeline failed to load");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { void loadTimeline(); }, [caseVersion, newestFirst]);

  async function addNote(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!activeCase) return;
    setLoading(true); onError(""); onNotice("");
    try {
      await request(`/api/investigations/${activeCase.investigation_id}/timeline/notes`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ author, note }),
      });
      setNote("");
      onNotice("Redacted operator note added to the immutable timeline.");
      await loadTimeline();
    } catch (caught) {
      onError(caught instanceof Error ? caught.message : "Operator note could not be added");
    } finally {
      setLoading(false);
    }
  }

  return <section id="timeline" className="timeline-workspace" aria-labelledby="timeline-title">
    <div className="section-heading"><span>Immutable case chronology</span><h2 id="timeline-title">Investigation timeline</h2></div>
    {!activeCase ? <p className="empty-state">Create or open an investigation to review its timeline.</p> : <>
      <div className="timeline-toolbar">
        <label><input type="checkbox" checked={newestFirst} onChange={(event) => setNewestFirst(event.target.checked)} />Newest events first</label>
        <button type="button" className="secondary" onClick={loadTimeline} disabled={unavailable || loading}>{loading ? "Refreshing…" : "Refresh timeline"}</button>
      </div>
      <form className="timeline-note-form" onSubmit={addNote}>
        <div><label htmlFor="timeline-author">Operator attribution</label><input id="timeline-author" value={author} onChange={(event) => setAuthor(event.target.value)} minLength={2} maxLength={80} required /></div>
        <div><label htmlFor="timeline-note">Redacted operator note</label><textarea id="timeline-note" value={note} onChange={(event) => setNote(event.target.value)} minLength={3} maxLength={1000} required /></div>
        <button type="submit" disabled={unavailable || loading || activeCase.status === "archived"}>Add timeline note</button>
      </form>
      {events.length === 0 ? <div className="empty-state"><strong>No timeline events yet.</strong><span>TRACE records system events when this case changes.</span></div> : <ol className="timeline-list">{events.map((event) => <li key={event.event_id} className={`timeline-event actor-${event.actor_type}`}>
        <div className="timeline-marker" aria-hidden="true" />
        <article>
          <header><strong>{label(event.event_type)}</strong><time dateTime={event.created_at}>{new Date(event.created_at).toLocaleString()}</time></header>
          <p>{event.summary}</p>
          <small>{event.actor_type === "system" ? "Generated by" : "Authored by"} {event.actor_label}</small>
          {Object.keys(event.details).length > 0 && <details><summary>Event details</summary><pre>{JSON.stringify(event.details, null, 2)}</pre></details>}
        </article>
      </li>)}</ol>}
    </>}
  </section>;
}
