import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";

import { TimelineWorkspace } from "./TimelineWorkspace";

const activeCase = {
  investigation_id: "trace-a1b2c3d4e5f6",
  status: "analyzed",
  evidence_item_count: 1,
  analysis_run_count: 1,
};

const events = [
  {
    event_id: 1,
    investigation_id: activeCase.investigation_id,
    created_at: "2026-07-14T08:00:00Z",
    event_type: "case_created",
    actor_type: "system",
    actor_label: "TRACE",
    summary: "Investigation created.",
    details: { scenario_type: "conditional_access" },
  },
  {
    event_id: 2,
    investigation_id: activeCase.investigation_id,
    created_at: "2026-07-14T08:05:00Z",
    event_type: "operator_note",
    actor_type: "operator",
    actor_label: "Rafael",
    summary: "Redacted escalation context added.",
    details: { redacted: true },
  },
];

afterEach(() => { cleanup(); vi.restoreAllMocks(); });

test("shows attributed system events and operator notes", async () => {
  vi.stubGlobal("fetch", vi.fn(async () => ({ ok: true, status: 200, json: async () => events })));
  render(<TimelineWorkspace activeCase={activeCase} unavailable={false} onError={vi.fn()} onNotice={vi.fn()} />);
  expect(await screen.findByRole("heading", { name: "Investigation timeline" })).toBeInTheDocument();
  expect(await screen.findByText("Investigation created.")).toBeInTheDocument();
  expect(screen.getByText("Generated by TRACE")).toBeInTheDocument();
  expect(screen.getByText("Authored by Rafael")).toBeInTheDocument();
});

test("adds a redacted operator note and refreshes the timeline", async () => {
  const onNotice = vi.fn();
  let current = events.slice(0, 1);
  const fetchMock = vi.fn(async (_input: RequestInfo | URL, init?: RequestInit) => {
    if (init?.method === "POST") {
      current = events;
      return { ok: true, status: 201, json: async () => events[1] };
    }
    return { ok: true, status: 200, json: async () => current };
  });
  vi.stubGlobal("fetch", fetchMock);
  render(<TimelineWorkspace activeCase={activeCase} unavailable={false} onError={vi.fn()} onNotice={onNotice} />);
  await screen.findByText("Investigation created.");
  fireEvent.change(screen.getByLabelText("Redacted operator note"), { target: { value: "Redacted escalation context added." } });
  fireEvent.click(screen.getByRole("button", { name: "Add timeline note" }));
  expect(await screen.findByText("Redacted escalation context added.")).toBeInTheDocument();
  expect(onNotice).toHaveBeenCalledWith("Redacted operator note added to the immutable timeline.");
  await waitFor(() => expect(fetchMock).toHaveBeenCalledWith(
    `/api/investigations/${activeCase.investigation_id}/timeline/notes`,
    expect.objectContaining({ method: "POST" }),
  ));
});
